M48
; DRILL file KiCad 10.0.3 date 2026-06-24T00:20:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-24T00:20:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.175
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X32.695Y-4.11
X32.695Y-21.89
X86.035Y-4.11
X86.035Y-21.89
T2
X0.35Y-47.1
X0.5Y-17.6
X59.5Y-17.6
X59.65Y-47.1
M30
