M48
; DRILL file KiCad 10.0.3 date 2026-06-25T14:53:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-25T14:53:13-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.175
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X21.702Y63.39
X21.702Y45.61
T2
X19.087Y34.11
X19.087Y4.6
X78.087Y34.11
X78.087Y4.6
M30
